### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by philippirsl** [agorf/trafficjam#1]
In execute bundle exec ruby trafficjam.rb a error ocurrend

trafficjam.rb:21: syntax error, unexpected ','
def send_email (subject:, body: '')

**Comment by philippirsl** [comment]
Ok, a fixit

**Comment by agorf** [comment]
Hi. Sorry for the late response, I just saw this.

This is a special syntax introduced in Ruby 2.1 for specifying a required keyword argument. So if you update Ruby to 2.1 or later, it will work.

If you don't want to update Ruby, you can add a dummy default value in the code:
```ruby
def send_email(subject: '', body: '')
  ...
end
```

**Comment by agorf** [comment]
I've also updated the script to remove the dependency on Ruby 2.1 so if you download it again, it should be OK.

**Comment by philippirsl** [comment]
Tks =)
